<?php

namespace ContainerS1iNeiv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QJ6FWAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qJ_6FWA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'langueRepo' => ['privates', 'App\\Repository\\LangueRepository', 'getLangueRepositoryService', true],
            'niveauRepo' => ['privates', 'App\\Repository\\NiveauRepository', 'getNiveauRepositoryService', true],
        ], [
            'em' => '?',
            'langueRepo' => 'App\\Repository\\LangueRepository',
            'niveauRepo' => 'App\\Repository\\NiveauRepository',
        ]);

        if (isset($container->privates['.service_locator.qJ_6FWA'])) {
            return $container->privates['.service_locator.qJ_6FWA'];
        }

        return $container->privates['.service_locator.qJ_6FWA'] = $instance;
    }
}
