<?php

namespace ContainerS1iNeiv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WzABoniService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WzABoni' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'langue' => ['privates', '.errored..service_locator.WzABoni.App\\Entity\\Langue', NULL, 'Cannot autowire service ".service_locator.WzABoni": it needs an instance of "App\\Entity\\Langue" but this type has been excluded in "config/services.yaml".'],
            'niveauRepository' => ['privates', 'App\\Repository\\NiveauRepository', 'getNiveauRepositoryService', true],
            'progressRepository' => ['privates', 'App\\Repository\\UserProgressRepository', 'getUserProgressRepositoryService', true],
            'testPassageRepository' => ['privates', 'App\\Repository\\TestPassageRepository', 'getTestPassageRepositoryService', true],
        ], [
            'coursRepository' => 'App\\Repository\\CoursRepository',
            'em' => '?',
            'langue' => 'App\\Entity\\Langue',
            'niveauRepository' => 'App\\Repository\\NiveauRepository',
            'progressRepository' => 'App\\Repository\\UserProgressRepository',
            'testPassageRepository' => 'App\\Repository\\TestPassageRepository',
        ]);

        if (isset($container->privates['.service_locator.WzABoni'])) {
            return $container->privates['.service_locator.WzABoni'];
        }

        return $container->privates['.service_locator.WzABoni'] = $instance;
    }
}
