<?php

namespace ContainerS1iNeiv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KgHrRwDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kgHrRwD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kgHrRwD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'langueRepository' => ['privates', 'App\\Repository\\LangueRepository', 'getLangueRepositoryService', true],
        ], [
            'langueRepository' => 'App\\Repository\\LangueRepository',
        ]);
    }
}
