<?php

namespace ContainerN0WKd9X;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FcqeXMyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fcqeXMy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\GroupeController::index' => ['privates', '.service_locator.__k1aJR', 'get_ServiceLocator_K1aJRService', true],
            'App\\Controller\\GroupeController::sendMessage' => ['privates', '.service_locator.1w628wh', 'get_ServiceLocator_1w628whService', true],
            'App\\Controller\\GroupeController::show' => ['privates', '.service_locator._iKdXRM', 'get_ServiceLocator_IKdXRMService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\GroupeController:index' => ['privates', '.service_locator.__k1aJR', 'get_ServiceLocator_K1aJRService', true],
            'App\\Controller\\GroupeController:sendMessage' => ['privates', '.service_locator.1w628wh', 'get_ServiceLocator_1w628whService', true],
            'App\\Controller\\GroupeController:show' => ['privates', '.service_locator._iKdXRM', 'get_ServiceLocator_IKdXRMService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\GroupeController::index' => '?',
            'App\\Controller\\GroupeController::sendMessage' => '?',
            'App\\Controller\\GroupeController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\GroupeController:index' => '?',
            'App\\Controller\\GroupeController:sendMessage' => '?',
            'App\\Controller\\GroupeController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.fcqeXMy'])) {
            return $container->privates['.service_locator.fcqeXMy'];
        }

        return $container->privates['.service_locator.fcqeXMy'] = $instance;
    }
}
