<?php

namespace ContainerN0WKd9X;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1w628whService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1w628wh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'groupe' => ['privates', '.errored..service_locator.1w628wh.App\\Entity\\Groupe', NULL, 'Cannot autowire service ".service_locator.1w628wh": it needs an instance of "App\\Entity\\Groupe" but this type has been excluded in "config/services.yaml".'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'em' => '?',
            'groupe' => 'App\\Entity\\Groupe',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.1w628wh'])) {
            return $container->privates['.service_locator.1w628wh'];
        }

        return $container->privates['.service_locator.1w628wh'] = $instance;
    }
}
