<?php

namespace ContainerEa0zKRc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TGvrhY1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TGvrhY1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passage' => ['privates', '.errored..service_locator.TGvrhY1.App\\Entity\\TestPassage', NULL, 'Cannot autowire service ".service_locator.TGvrhY1": it needs an instance of "App\\Entity\\TestPassage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'passage' => 'App\\Entity\\TestPassage',
        ]);

        if (isset($container->privates['.service_locator.TGvrhY1'])) {
            return $container->privates['.service_locator.TGvrhY1'];
        }

        return $container->privates['.service_locator.TGvrhY1'] = $instance;
    }
}
