<?php

namespace ContainerKm2rDhd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_StateMachine_TestPassage_Listener_AuditTrailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.state_machine.test_passage.listener.audit_trail' shared service.
     *
     * @return \Symfony\Component\Workflow\EventListener\AuditTrailListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'workflow'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'AuditTrailListener.php';

        $a = new \Monolog\Logger('workflow');
        $a->pushHandler(($container->privates['monolog.handler.console'] ?? self::getMonolog_Handler_ConsoleService($container)));
        $a->pushHandler(($container->privates['monolog.handler.main'] ?? self::getMonolog_Handler_MainService($container)));
        ($container->privates['debug.debug_logger_configurator'] ?? self::getDebug_DebugLoggerConfiguratorService($container))->pushDebugLogger($a);

        return $container->privates['.state_machine.test_passage.listener.audit_trail'] = new \Symfony\Component\Workflow\EventListener\AuditTrailListener($a);
    }
}
