<?php

namespace ContainerKm2rDhd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDictionaryServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\DictionaryService' shared autowired service.
     *
     * @return \App\Service\DictionaryService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'DictionaryService.php';

        return $container->privates['App\\Service\\DictionaryService'] = new \App\Service\DictionaryService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
