<?php

namespace ContainerPTrl0Se;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5AOWLhaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5AOWLha' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'langue' => ['privates', '.errored..service_locator.5AOWLha.App\\Entity\\Langue', NULL, 'Cannot autowire service ".service_locator.5AOWLha": it needs an instance of "App\\Entity\\Langue" but this type has been excluded in "config/services.yaml".'],
        ], [
            'coursRepository' => 'App\\Repository\\CoursRepository',
            'em' => '?',
            'langue' => 'App\\Entity\\Langue',
        ]);

        if (isset($container->privates['.service_locator.5AOWLha'])) {
            return $container->privates['.service_locator.5AOWLha'];
        }

        return $container->privates['.service_locator.5AOWLha'] = $instance;
    }
}
