<?php

namespace ContainerTQq9byZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tf3ck_KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tf3ck.K' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'groupeRepository' => ['privates', 'App\\Repository\\GroupeRepository', 'getGroupeRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
        ], [
            'em' => '?',
            'groupeRepository' => 'App\\Repository\\GroupeRepository',
            'paginator' => '?',
            'sessionRepository' => 'App\\Repository\\SessionRepository',
        ]);

        if (isset($container->privates['.service_locator.tf3ck.K'])) {
            return $container->privates['.service_locator.tf3ck.K'];
        }

        return $container->privates['.service_locator.tf3ck.K'] = $instance;
    }
}
