<?php

namespace ContainerTQq9byZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_StateMachine_TestPassage_Listener_GuardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.state_machine.test_passage.listener.guard' shared service.
     *
     * @return \Symfony\Component\Workflow\EventListener\GuardListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'workflow'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'GuardListener.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'workflow'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'GuardExpression.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'Authorization'.\DIRECTORY_SEPARATOR.'ExpressionLanguage.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'workflow'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'ExpressionLanguage.php';

        $a = ($container->privates['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container));

        if (isset($container->privates['.state_machine.test_passage.listener.guard'])) {
            return $container->privates['.state_machine.test_passage.listener.guard'];
        }
        $b = ($container->privates['debug.validator'] ?? self::getDebug_ValidatorService($container));

        if (isset($container->privates['.state_machine.test_passage.listener.guard'])) {
            return $container->privates['.state_machine.test_passage.listener.guard'];
        }

        $instance = new \Symfony\Component\Workflow\EventListener\GuardListener(['workflow.test_passage.guard.soumettre' => [new \Symfony\Component\Workflow\EventListener\GuardExpression(($container->privates['.state_machine.test_passage.transition.3'] ??= new \Symfony\Component\Workflow\Transition('soumettre', 'en_cours', 'soumis')), 'subject.getStatut() in [\'en_cours\', \'en_pause\']'), new \Symfony\Component\Workflow\EventListener\GuardExpression(($container->privates['.state_machine.test_passage.transition.4'] ??= new \Symfony\Component\Workflow\Transition('soumettre', 'en_pause', 'soumis')), 'subject.getStatut() in [\'en_cours\', \'en_pause\']')]], new \Symfony\Component\Workflow\EventListener\ExpressionLanguage(), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), $a, ($container->privates['security.authentication.trust_resolver'] ??= new \Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolver()), ($container->privates['security.role_hierarchy'] ??= new \Symfony\Component\Security\Core\Role\RoleHierarchy([])), $b);

        if (isset($container->privates['.state_machine.test_passage.listener.guard'])) {
            return $container->privates['.state_machine.test_passage.listener.guard'];
        }

        return $container->privates['.state_machine.test_passage.listener.guard'] = $instance;
    }
}
