<?php

namespace ContainerTQq9byZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLanguageStatsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\LanguageStatsService' shared autowired service.
     *
     * @return \App\Service\LanguageStatsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'LanguageStatsService.php';

        return $container->privates['App\\Service\\LanguageStatsService'] = new \App\Service\LanguageStatsService(($container->services['cache.app'] ?? self::getCache_AppService($container)));
    }
}
