<?php

namespace Container3E22rxU;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4byctLcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4byctLc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passage' => ['privates', '.errored..service_locator.4byctLc.App\\Entity\\TestPassage', NULL, 'Cannot autowire service ".service_locator.4byctLc": it needs an instance of "App\\Entity\\TestPassage" but this type has been excluded in "config/services.yaml".'],
            'testPassageStateMachine' => ['privates', 'debug.state_machine.test_passage', 'getDebug_StateMachine_TestPassageService', false],
        ], [
            'em' => '?',
            'passage' => 'App\\Entity\\TestPassage',
            'testPassageStateMachine' => '?',
        ]);

        if (isset($container->privates['.service_locator.4byctLc'])) {
            return $container->privates['.service_locator.4byctLc'];
        }

        return $container->privates['.service_locator.4byctLc'] = $instance;
    }
}
