<?php

namespace Container3E22rxU;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__BkQBeYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..BkQBeY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'groupe' => ['privates', '.errored..service_locator..BkQBeY.App\\Entity\\Groupe', NULL, 'Cannot autowire service ".service_locator..BkQBeY": it needs an instance of "App\\Entity\\Groupe" but this type has been excluded in "config/services.yaml".'],
            'http' => ['privates', '.debug.http_client', 'get_Debug_HttpClientService', false],
        ], [
            'em' => '?',
            'groupe' => 'App\\Entity\\Groupe',
            'http' => '?',
        ]);

        if (isset($container->privates['.service_locator..BkQBeY'])) {
            return $container->privates['.service_locator..BkQBeY'];
        }

        return $container->privates['.service_locator..BkQBeY'] = $instance;
    }
}
