<?php

namespace Container3E22rxU;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestPassage3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cIiZuvt.App\Entity\TestPassage' shared service.
     *
     * @return \App\Entity\TestPassage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.cIiZuvt": it needs an instance of "App\\Entity\\TestPassage" but this type has been excluded in "config/services.yaml".');
    }
}
