<?php

namespace ContainerHr0s0ei;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UQDmSxAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uQDmSxA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'paginator' => ['privates', '.errored.HrfBsYu', NULL, 'Cannot determine controller argument for "App\\Controller\\SessionController::adminIndex()": the $paginator argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
        ], [
            'entityManager' => '?',
            'paginator' => '?',
            'sessionRepository' => 'App\\Repository\\SessionRepository',
        ]);

        if (isset($container->privates['.service_locator.uQDmSxA'])) {
            return $container->privates['.service_locator.uQDmSxA'];
        }

        return $container->privates['.service_locator.uQDmSxA'] = $instance;
    }
}
