<?php

namespace ContainerHr0s0ei;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PtBgJH4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PtBgJH4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PtBgJH4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['privates', '.errored.psllLhj', NULL, 'Cannot determine controller argument for "App\\Controller\\SessionController::frontIndex()": the $paginator argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
        ], [
            'paginator' => '?',
            'sessionRepository' => 'App\\Repository\\SessionRepository',
        ]);
    }
}
