<?php

namespace ContainerHr0s0ei;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HW9aXHqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HW9aXHq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'paginator' => ['privates', '.errored.XnDOLxg', NULL, 'Cannot determine controller argument for "App\\Controller\\ReservationController::adminIndex()": the $paginator argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'entityManager' => '?',
            'paginator' => '?',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
        ]);

        if (isset($container->privates['.service_locator.HW9aXHq'])) {
            return $container->privates['.service_locator.HW9aXHq'];
        }

        return $container->privates['.service_locator.HW9aXHq'] = $instance;
    }
}
