<?php

namespace ContainerHr0s0ei;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QWSWklService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._qWSWkl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._qWSWkl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['privates', '.errored.p0oQd17', NULL, 'Cannot determine controller argument for "App\\Controller\\ReservationController::frontIndex()": the $paginator argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
        ], [
            'paginator' => '?',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
        ]);
    }
}
