<?php

namespace ContainerTOR5YDI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_22sTr4zService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.22sTr4z' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'messenger'.\DIRECTORY_SEPARATOR.'Handler'.\DIRECTORY_SEPARATOR.'HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'MessageHandler'.\DIRECTORY_SEPARATOR.'GenererCoursHandler.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['.messenger.handler_descriptor.22sTr4z'])) {
            return $container->privates['.messenger.handler_descriptor.22sTr4z'];
        }

        $instance = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\MessageHandler\GenererCoursHandler($a), []);

        if (isset($container->privates['.messenger.handler_descriptor.22sTr4z'])) {
            return $container->privates['.messenger.handler_descriptor.22sTr4z'];
        }

        return $container->privates['.messenger.handler_descriptor.22sTr4z'] = $instance;
    }
}
