<?php

namespace ContainerTOR5YDI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KSXKpxNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kSXKpxN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'langue' => ['privates', '.errored..service_locator.kSXKpxN.App\\Entity\\Langue', NULL, 'Cannot autowire service ".service_locator.kSXKpxN": it needs an instance of "App\\Entity\\Langue" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'em' => '?',
            'langue' => 'App\\Entity\\Langue',
            'slugger' => '?',
        ]);

        if (isset($container->privates['.service_locator.kSXKpxN'])) {
            return $container->privates['.service_locator.kSXKpxN'];
        }

        return $container->privates['.service_locator.kSXKpxN'] = $instance;
    }
}
