<?php

namespace ContainerTNsoxN3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K1aJRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.__k1aJR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.__k1aJR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'groupeRepository' => ['privates', 'App\\Repository\\GroupeRepository', 'getGroupeRepositoryService', true],
        ], [
            'groupeRepository' => 'App\\Repository\\GroupeRepository',
        ]);
    }
}
