<?php

namespace ContainerTNsoxN3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4IoEfhdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4IoEfhd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4IoEfhd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'langue' => ['privates', '.errored..service_locator.4IoEfhd.App\\Entity\\Langue', NULL, 'Cannot autowire service ".service_locator.4IoEfhd": it needs an instance of "App\\Entity\\Langue" but this type has been excluded in "config/services.yaml".'],
        ], [
            'langue' => 'App\\Entity\\Langue',
        ]);
    }
}
