<?php

namespace ContainerTNsoxN3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Aww2xGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..aww2xG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cour' => ['privates', '.errored..service_locator..aww2xG.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator..aww2xG": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'cour' => 'App\\Entity\\Cours',
            'em' => '?',
            'slugger' => '?',
        ]);

        if (isset($container->privates['.service_locator..aww2xG'])) {
            return $container->privates['.service_locator..aww2xG'];
        }

        return $container->privates['.service_locator..aww2xG'] = $instance;
    }
}
