<?php

namespace ContainerTNsoxN3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCours2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4Oqb_AZ.App\Entity\Cours' shared service.
     *
     * @return \App\Entity\Cours
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4Oqb_AZ": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".');
    }
}
