<?php

namespace Container72YNBLX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mi6yUpXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Mi6yUpX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Mi6yUpX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'gameService' => ['privates', 'App\\Service\\GameService', 'getGameServiceService', true],
        ], [
            'gameService' => 'App\\Service\\GameService',
        ]);
    }
}
