<?php

namespace Container72YNBLX;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8Um2rfAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8Um2rfA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8Um2rfA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'groupeRepo' => ['privates', 'App\\Repository\\GroupeRepository', 'getGroupeRepositoryService', true],
            'langueRepo' => ['privates', 'App\\Repository\\LangueRepository', 'getLangueRepositoryService', true],
            'niveauRepo' => ['privates', 'App\\Repository\\NiveauRepository', 'getNiveauRepositoryService', true],
        ], [
            'groupeRepo' => 'App\\Repository\\GroupeRepository',
            'langueRepo' => 'App\\Repository\\LangueRepository',
            'niveauRepo' => 'App\\Repository\\NiveauRepository',
        ]);
    }
}
