<?php

namespace ContainerCHTdrgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FAsumiQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FAsumiQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FAsumiQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'langueRepository' => ['privates', 'App\\Repository\\LangueRepository', 'getLangueRepositoryService', true],
            'niveauRepository' => ['privates', 'App\\Repository\\NiveauRepository', 'getNiveauRepositoryService', true],
        ], [
            'langueRepository' => 'App\\Repository\\LangueRepository',
            'niveauRepository' => 'App\\Repository\\NiveauRepository',
        ]);
    }
}
