<?php

namespace ContainerCHTdrgH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestWorkflowSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\TestWorkflowSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\TestWorkflowSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'TestWorkflowSubscriber.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'];
        }
        $b = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'];
        }

        $instance = new \App\EventSubscriber\TestWorkflowSubscriber($a, $b, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        if (isset($container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'] = $instance;
    }
}
