<?php

namespace ContainerGRHZZTT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_36BVlTsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.36BVlTs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.36BVlTs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'groupe' => ['privates', '.errored..service_locator.36BVlTs.App\\Entity\\Groupe', NULL, 'Cannot autowire service ".service_locator.36BVlTs": it needs an instance of "App\\Entity\\Groupe" but this type has been excluded in "config/services.yaml".'],
            'logRepo' => ['privates', 'App\\Repository\\MessageLogRepository', 'getMessageLogRepositoryService', true],
            'messageRepo' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
        ], [
            'groupe' => 'App\\Entity\\Groupe',
            'logRepo' => 'App\\Repository\\MessageLogRepository',
            'messageRepo' => 'App\\Repository\\MessageRepository',
        ]);
    }
}
