<?php

namespace ContainerGRHZZTT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LpTi80XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LpTi80X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
        ], [
            'entityManager' => '?',
            'paginator' => '?',
            'sessionRepository' => 'App\\Repository\\SessionRepository',
        ]);

        if (isset($container->privates['.service_locator.LpTi80X'])) {
            return $container->privates['.service_locator.LpTi80X'];
        }

        return $container->privates['.service_locator.LpTi80X'] = $instance;
    }
}
