<?php

namespace ContainerGRHZZTT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAITextCorrectionServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AITextCorrectionService' shared autowired service.
     *
     * @return \App\Service\AITextCorrectionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AITextCorrectionService.php';

        return $container->privates['App\\Service\\AITextCorrectionService'] = new \App\Service\AITextCorrectionService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('GROQ_API_KEY'), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
