<?php

namespace ContainerBgkr5vd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6NDrKwtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6NDrKwt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'groupe' => ['privates', '.errored..service_locator.6NDrKwt.App\\Entity\\Groupe', NULL, 'Cannot autowire service ".service_locator.6NDrKwt": it needs an instance of "App\\Entity\\Groupe" but this type has been excluded in "config/services.yaml".'],
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'progressRepo' => ['privates', 'App\\Repository\\UserProgressRepository', 'getUserProgressRepositoryService', true],
        ], [
            'em' => '?',
            'groupe' => 'App\\Entity\\Groupe',
            'messageRepository' => 'App\\Repository\\MessageRepository',
            'paginator' => '?',
            'progressRepo' => 'App\\Repository\\UserProgressRepository',
        ]);

        if (isset($container->privates['.service_locator.6NDrKwt'])) {
            return $container->privates['.service_locator.6NDrKwt'];
        }

        return $container->privates['.service_locator.6NDrKwt'] = $instance;
    }
}
