<?php

namespace ContainerBgkr5vd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NQ9KGA7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nQ9KGA7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authenticator' => ['privates', 'App\\Security\\LoginFormAuthenticator', 'getLoginFormAuthenticatorService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'userAuthenticator' => ['privates', 'security.user_authenticator', 'getSecurity_UserAuthenticatorService', true],
        ], [
            'authenticator' => 'App\\Security\\LoginFormAuthenticator',
            'em' => '?',
            'mailer' => '?',
            'userAuthenticator' => '?',
        ]);

        if (isset($container->privates['.service_locator.nQ9KGA7'])) {
            return $container->privates['.service_locator.nQ9KGA7'];
        }

        return $container->privates['.service_locator.nQ9KGA7'] = $instance;
    }
}
