<?php

namespace ContainerBgkr5vd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestScoringServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TestScoringService' shared autowired service.
     *
     * @return \App\Service\TestScoringService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TestScoringService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SpeechEvaluationService.php';

        return $container->privates['App\\Service\\TestScoringService'] = new \App\Service\TestScoringService(($container->privates['App\\Repository\\ReponseRepository'] ?? $container->load('getReponseRepositoryService')), new \App\Service\SpeechEvaluationService());
    }
}
