<?php

namespace ContainerBgkr5vd;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestPassage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.bL44EFS.App\Entity\TestPassage' shared service.
     *
     * @return \App\Entity\TestPassage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.bL44EFS": it needs an instance of "App\\Entity\\TestPassage" but this type has been excluded in "config/services.yaml".');
    }
}
