<?php

namespace Container0OLkGg3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gl6lAV6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gl6lAV6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'groupe' => ['privates', '.errored..service_locator.Gl6lAV6.App\\Entity\\Groupe', NULL, 'Cannot autowire service ".service_locator.Gl6lAV6": it needs an instance of "App\\Entity\\Groupe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'groupe' => 'App\\Entity\\Groupe',
        ]);

        if (isset($container->privates['.service_locator.Gl6lAV6'])) {
            return $container->privates['.service_locator.Gl6lAV6'];
        }

        return $container->privates['.service_locator.Gl6lAV6'] = $instance;
    }
}
