<?php

namespace Container0OLkGg3;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Gl6lAV6.App\Entity\Groupe' shared service.
     *
     * @return \App\Entity\Groupe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Gl6lAV6": it needs an instance of "App\\Entity\\Groupe" but this type has been excluded in "config/services.yaml".');
    }
}
