<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Test extends \App\Entity\Test implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Id_langue' => [parent::class, 'Id_langue', null, 16],
        "\0".parent::class."\0".'Id_user' => [parent::class, 'Id_user', null, 16],
        "\0".parent::class."\0".'date_passage' => [parent::class, 'date_passage', null, 16],
        "\0".parent::class."\0".'duree' => [parent::class, 'duree', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'questions' => [parent::class, 'questions', null, 16],
        "\0".parent::class."\0".'resultat' => [parent::class, 'resultat', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        'Id_langue' => [parent::class, 'Id_langue', null, 16],
        'Id_user' => [parent::class, 'Id_user', null, 16],
        'date_passage' => [parent::class, 'date_passage', null, 16],
        'duree' => [parent::class, 'duree', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'questions' => [parent::class, 'questions', null, 16],
        'resultat' => [parent::class, 'resultat', null, 16],
        'type' => [parent::class, 'type', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
