<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Niveau extends \App\Entity\Niveau implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Id_langue' => [parent::class, 'Id_langue', null, 16],
        "\0".parent::class."\0".'cours' => [parent::class, 'cours', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'difficulte' => [parent::class, 'difficulte', null, 16],
        "\0".parent::class."\0".'groupes' => [parent::class, 'groupes', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'image_couverture' => [parent::class, 'image_couverture', null, 16],
        "\0".parent::class."\0".'ordre' => [parent::class, 'ordre', null, 16],
        "\0".parent::class."\0".'seuil_score_max' => [parent::class, 'seuil_score_max', null, 16],
        "\0".parent::class."\0".'seuil_score_min' => [parent::class, 'seuil_score_min', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        'Id_langue' => [parent::class, 'Id_langue', null, 16],
        'cours' => [parent::class, 'cours', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'difficulte' => [parent::class, 'difficulte', null, 16],
        'groupes' => [parent::class, 'groupes', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'image_couverture' => [parent::class, 'image_couverture', null, 16],
        'ordre' => [parent::class, 'ordre', null, 16],
        'seuil_score_max' => [parent::class, 'seuil_score_max', null, 16],
        'seuil_score_min' => [parent::class, 'seuil_score_min', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
