<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Langue extends \App\Entity\Langue implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Id_user' => [parent::class, 'Id_user', null, 16],
        "\0".parent::class."\0".'date_ajout' => [parent::class, 'date_ajout', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'drapeau' => [parent::class, 'drapeau', null, 16],
        "\0".parent::class."\0".'drapeauFile' => [parent::class, 'drapeauFile', null, 16],
        "\0".parent::class."\0".'groupes' => [parent::class, 'groupes', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'is_active' => [parent::class, 'is_active', null, 16],
        "\0".parent::class."\0".'niveaux' => [parent::class, 'niveaux', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'popularite' => [parent::class, 'popularite', null, 16],
        "\0".parent::class."\0".'tests' => [parent::class, 'tests', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'Id_user' => [parent::class, 'Id_user', null, 16],
        'date_ajout' => [parent::class, 'date_ajout', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'drapeau' => [parent::class, 'drapeau', null, 16],
        'drapeauFile' => [parent::class, 'drapeauFile', null, 16],
        'groupes' => [parent::class, 'groupes', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'is_active' => [parent::class, 'is_active', null, 16],
        'niveaux' => [parent::class, 'niveaux', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'popularite' => [parent::class, 'popularite', null, 16],
        'tests' => [parent::class, 'tests', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
