<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Objectif extends \App\Entity\Objectif implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Id_user' => [parent::class, 'Id_user', null, 16],
        "\0".parent::class."\0".'date_deb' => [parent::class, 'date_deb', null, 16],
        "\0".parent::class."\0".'date_fin' => [parent::class, 'date_fin', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'taches' => [parent::class, 'taches', null, 16],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null, 16],
        'Id_user' => [parent::class, 'Id_user', null, 16],
        'date_deb' => [parent::class, 'date_deb', null, 16],
        'date_fin' => [parent::class, 'date_fin', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'taches' => [parent::class, 'taches', null, 16],
        'titre' => [parent::class, 'titre', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
