<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cours extends \App\Entity\Cours implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Id_niveau' => [parent::class, 'Id_niveau', null, 16],
        "\0".parent::class."\0".'cours' => [parent::class, 'cours', null, 16],
        "\0".parent::class."\0".'cours_precedent_id' => [parent::class, 'cours_precedent_id', null, 16],
        "\0".parent::class."\0".'date_creation' => [parent::class, 'date_creation', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'numero' => [parent::class, 'numero', null, 16],
        "\0".parent::class."\0".'ressource' => [parent::class, 'ressource', null, 16],
        'Id_niveau' => [parent::class, 'Id_niveau', null, 16],
        'cours' => [parent::class, 'cours', null, 16],
        'cours_precedent_id' => [parent::class, 'cours_precedent_id', null, 16],
        'date_creation' => [parent::class, 'date_creation', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'numero' => [parent::class, 'numero', null, 16],
        'ressource' => [parent::class, 'ressource', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
