<?php

namespace Container9axBOKx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YYv4yfmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YYv4yfm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YYv4yfm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'langue' => ['privates', '.errored..service_locator.YYv4yfm.App\\Entity\\Langue', NULL, 'Cannot autowire service ".service_locator.YYv4yfm": it needs an instance of "App\\Entity\\Langue" but this type has been excluded in "config/services.yaml".'],
        ], [
            'coursRepository' => 'App\\Repository\\CoursRepository',
            'langue' => 'App\\Entity\\Langue',
        ]);
    }
}
