<?php

namespace ContainerUXCgiCZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RPP6y3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R_PP6y3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'niveau' => ['privates', '.errored..service_locator.R_PP6y3.App\\Entity\\Niveau', NULL, 'Cannot autowire service ".service_locator.R_PP6y3": it needs an instance of "App\\Entity\\Niveau" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'niveau' => 'App\\Entity\\Niveau',
        ]);

        if (isset($container->privates['.service_locator.R_PP6y3'])) {
            return $container->privates['.service_locator.R_PP6y3'];
        }

        return $container->privates['.service_locator.R_PP6y3'] = $instance;
    }
}
