<?php

namespace ContainerUXCgiCZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1hNKMORService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1hNKMOR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1hNKMOR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'testPassageRepository' => ['privates', 'App\\Repository\\TestPassageRepository', 'getTestPassageRepositoryService', true],
        ], [
            'testPassageRepository' => 'App\\Repository\\TestPassageRepository',
        ]);
    }
}
