<?php

namespace ContainerUXCgiCZ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecommandationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RecommandationController' shared autowired service.
     *
     * @return \App\Controller\RecommandationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'RecommandationController.php';

        $container->services['App\\Controller\\RecommandationController'] = $instance = new \App\Controller\RecommandationController(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));

        $instance->setContainer(($container->privates['.service_locator.a_BEVU0'] ?? $container->load('get_ServiceLocator_ABEVU0Service'))->withContext('App\\Controller\\RecommandationController', $container));

        return $instance;
    }
}
