<?php

namespace ContainerFAJuXMs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IHX5D5_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iHX5D5.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iHX5D5.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'langueRepository' => ['privates', 'App\\Repository\\LangueRepository', 'getLangueRepositoryService', true],
            'statsService' => ['privates', 'App\\Service\\LanguageStatsService', 'getLanguageStatsServiceService', true],
        ], [
            'langueRepository' => 'App\\Repository\\LangueRepository',
            'statsService' => 'App\\Service\\LanguageStatsService',
        ]);
    }
}
