<?php

namespace ContainerFAJuXMs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O6MN54lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o6MN54l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CoursController::adminShow' => ['privates', '.service_locator.eeiR1bl', 'get_ServiceLocator_EeiR1blService', true],
            'App\\Controller\\CoursController::delete' => ['privates', '.service_locator.BHmLGFq', 'get_ServiceLocator_BHmLGFqService', true],
            'App\\Controller\\CoursController::edit' => ['privates', '.service_locator..aww2xG', 'get_ServiceLocator__Aww2xGService', true],
            'App\\Controller\\CoursController::index' => ['privates', '.service_locator.XXl0e8G', 'get_ServiceLocator_XXl0e8GService', true],
            'App\\Controller\\CoursController::new' => ['privates', '.service_locator.P3uOD4s', 'get_ServiceLocator_P3uOD4sService', true],
            'App\\Controller\\CoursController::show' => ['privates', '.service_locator.eeiR1bl', 'get_ServiceLocator_EeiR1blService', true],
            'App\\Controller\\CoursController::terminer' => ['privates', '.service_locator.fSiFUO9', 'get_ServiceLocator_FSiFUO9Service', true],
            'App\\Controller\\LangueController::apprentissage' => ['privates', '.service_locator.YYv4yfm', 'get_ServiceLocator_YYv4yfmService', true],
            'App\\Controller\\LangueController::delete' => ['privates', '.service_locator.BPUmrO7', 'get_ServiceLocator_BPUmrO7Service', true],
            'App\\Controller\\LangueController::edit' => ['privates', '.service_locator.kSXKpxN', 'get_ServiceLocator_KSXKpxNService', true],
            'App\\Controller\\LangueController::indexAdmin' => ['privates', '.service_locator.kgHrRwD', 'get_ServiceLocator_KgHrRwDService', true],
            'App\\Controller\\LangueController::indexEtudiant' => ['privates', '.service_locator.kgHrRwD', 'get_ServiceLocator_KgHrRwDService', true],
            'App\\Controller\\LangueController::new' => ['privates', '.service_locator.P3uOD4s', 'get_ServiceLocator_P3uOD4sService', true],
            'App\\Controller\\LangueController::show' => ['privates', '.service_locator.4IoEfhd', 'get_ServiceLocator_4IoEfhdService', true],
            'App\\Controller\\LangueController::statsAdmin' => ['privates', '.service_locator.iHX5D5.', 'get_ServiceLocator_IHX5D5_Service', true],
            'App\\Controller\\NiveauController::delete' => ['privates', '.service_locator.R_PP6y3', 'get_ServiceLocator_RPP6y3Service', true],
            'App\\Controller\\NiveauController::edit' => ['privates', '.service_locator.jkbq_QJ', 'get_ServiceLocator_JkbqQJService', true],
            'App\\Controller\\NiveauController::index' => ['privates', '.service_locator.FAsumiQ', 'get_ServiceLocator_FAsumiQService', true],
            'App\\Controller\\NiveauController::new' => ['privates', '.service_locator.P3uOD4s', 'get_ServiceLocator_P3uOD4sService', true],
            'App\\Controller\\NiveauController::show' => ['privates', '.service_locator.o5jMG29', 'get_ServiceLocator_O5jMG29Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CoursController:adminShow' => ['privates', '.service_locator.eeiR1bl', 'get_ServiceLocator_EeiR1blService', true],
            'App\\Controller\\CoursController:delete' => ['privates', '.service_locator.BHmLGFq', 'get_ServiceLocator_BHmLGFqService', true],
            'App\\Controller\\CoursController:edit' => ['privates', '.service_locator..aww2xG', 'get_ServiceLocator__Aww2xGService', true],
            'App\\Controller\\CoursController:index' => ['privates', '.service_locator.XXl0e8G', 'get_ServiceLocator_XXl0e8GService', true],
            'App\\Controller\\CoursController:new' => ['privates', '.service_locator.P3uOD4s', 'get_ServiceLocator_P3uOD4sService', true],
            'App\\Controller\\CoursController:show' => ['privates', '.service_locator.eeiR1bl', 'get_ServiceLocator_EeiR1blService', true],
            'App\\Controller\\CoursController:terminer' => ['privates', '.service_locator.fSiFUO9', 'get_ServiceLocator_FSiFUO9Service', true],
            'App\\Controller\\LangueController:apprentissage' => ['privates', '.service_locator.YYv4yfm', 'get_ServiceLocator_YYv4yfmService', true],
            'App\\Controller\\LangueController:delete' => ['privates', '.service_locator.BPUmrO7', 'get_ServiceLocator_BPUmrO7Service', true],
            'App\\Controller\\LangueController:edit' => ['privates', '.service_locator.kSXKpxN', 'get_ServiceLocator_KSXKpxNService', true],
            'App\\Controller\\LangueController:indexAdmin' => ['privates', '.service_locator.kgHrRwD', 'get_ServiceLocator_KgHrRwDService', true],
            'App\\Controller\\LangueController:indexEtudiant' => ['privates', '.service_locator.kgHrRwD', 'get_ServiceLocator_KgHrRwDService', true],
            'App\\Controller\\LangueController:new' => ['privates', '.service_locator.P3uOD4s', 'get_ServiceLocator_P3uOD4sService', true],
            'App\\Controller\\LangueController:show' => ['privates', '.service_locator.4IoEfhd', 'get_ServiceLocator_4IoEfhdService', true],
            'App\\Controller\\LangueController:statsAdmin' => ['privates', '.service_locator.iHX5D5.', 'get_ServiceLocator_IHX5D5_Service', true],
            'App\\Controller\\NiveauController:delete' => ['privates', '.service_locator.R_PP6y3', 'get_ServiceLocator_RPP6y3Service', true],
            'App\\Controller\\NiveauController:edit' => ['privates', '.service_locator.jkbq_QJ', 'get_ServiceLocator_JkbqQJService', true],
            'App\\Controller\\NiveauController:index' => ['privates', '.service_locator.FAsumiQ', 'get_ServiceLocator_FAsumiQService', true],
            'App\\Controller\\NiveauController:new' => ['privates', '.service_locator.P3uOD4s', 'get_ServiceLocator_P3uOD4sService', true],
            'App\\Controller\\NiveauController:show' => ['privates', '.service_locator.o5jMG29', 'get_ServiceLocator_O5jMG29Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CoursController::adminShow' => '?',
            'App\\Controller\\CoursController::delete' => '?',
            'App\\Controller\\CoursController::edit' => '?',
            'App\\Controller\\CoursController::index' => '?',
            'App\\Controller\\CoursController::new' => '?',
            'App\\Controller\\CoursController::show' => '?',
            'App\\Controller\\CoursController::terminer' => '?',
            'App\\Controller\\LangueController::apprentissage' => '?',
            'App\\Controller\\LangueController::delete' => '?',
            'App\\Controller\\LangueController::edit' => '?',
            'App\\Controller\\LangueController::indexAdmin' => '?',
            'App\\Controller\\LangueController::indexEtudiant' => '?',
            'App\\Controller\\LangueController::new' => '?',
            'App\\Controller\\LangueController::show' => '?',
            'App\\Controller\\LangueController::statsAdmin' => '?',
            'App\\Controller\\NiveauController::delete' => '?',
            'App\\Controller\\NiveauController::edit' => '?',
            'App\\Controller\\NiveauController::index' => '?',
            'App\\Controller\\NiveauController::new' => '?',
            'App\\Controller\\NiveauController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CoursController:adminShow' => '?',
            'App\\Controller\\CoursController:delete' => '?',
            'App\\Controller\\CoursController:edit' => '?',
            'App\\Controller\\CoursController:index' => '?',
            'App\\Controller\\CoursController:new' => '?',
            'App\\Controller\\CoursController:show' => '?',
            'App\\Controller\\CoursController:terminer' => '?',
            'App\\Controller\\LangueController:apprentissage' => '?',
            'App\\Controller\\LangueController:delete' => '?',
            'App\\Controller\\LangueController:edit' => '?',
            'App\\Controller\\LangueController:indexAdmin' => '?',
            'App\\Controller\\LangueController:indexEtudiant' => '?',
            'App\\Controller\\LangueController:new' => '?',
            'App\\Controller\\LangueController:show' => '?',
            'App\\Controller\\LangueController:statsAdmin' => '?',
            'App\\Controller\\NiveauController:delete' => '?',
            'App\\Controller\\NiveauController:edit' => '?',
            'App\\Controller\\NiveauController:index' => '?',
            'App\\Controller\\NiveauController:new' => '?',
            'App\\Controller\\NiveauController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.o6MN54l'])) {
            return $container->privates['.service_locator.o6MN54l'];
        }

        return $container->privates['.service_locator.o6MN54l'] = $instance;
    }
}
