<?php

namespace Container8CpMxTh;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YyKvHeLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YyKvHeL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'analyzer' => ['privates', 'App\\Service\\PerformanceAnalyzerService', 'getPerformanceAnalyzerServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'analyzer' => 'App\\Service\\PerformanceAnalyzerService',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.YyKvHeL'])) {
            return $container->privates['.service_locator.YyKvHeL'];
        }

        return $container->privates['.service_locator.YyKvHeL'] = $instance;
    }
}
