<?php

namespace Container8CpMxTh;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QdW0IH1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qdW0IH1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'client' => ['privates', '.debug.http_client', 'get_Debug_HttpClientService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'message' => ['privates', '.errored..service_locator.qdW0IH1.App\\Entity\\Message', NULL, 'Cannot autowire service ".service_locator.qdW0IH1": it needs an instance of "App\\Entity\\Message" but this type has been excluded in "config/services.yaml".'],
        ], [
            'client' => '?',
            'em' => '?',
            'message' => 'App\\Entity\\Message',
        ]);

        if (isset($container->privates['.service_locator.qdW0IH1'])) {
            return $container->privates['.service_locator.qdW0IH1'];
        }

        return $container->privates['.service_locator.qdW0IH1'] = $instance;
    }
}
