<?php

namespace Container9s8x2yl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sv74F8bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sv74F8b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\DashboardController::deleteUser' => ['privates', '.service_locator.LLEuAX_', 'get_ServiceLocator_LLEuAXService', true],
            'App\\Controller\\DashboardController::editUser' => ['privates', '.service_locator.81LTOQ7', 'get_ServiceLocator_81LTOQ7Service', true],
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\LoginController::logout' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\LoginController::logoutAjax' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProfileController::index' => ['privates', '.service_locator.81LTOQ7', 'get_ServiceLocator_81LTOQ7Service', true],
            'App\\Controller\\RegisterController::index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\DashboardController:deleteUser' => ['privates', '.service_locator.LLEuAX_', 'get_ServiceLocator_LLEuAXService', true],
            'App\\Controller\\DashboardController:editUser' => ['privates', '.service_locator.81LTOQ7', 'get_ServiceLocator_81LTOQ7Service', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\LoginController:logout' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\LoginController:logoutAjax' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProfileController:index' => ['privates', '.service_locator.81LTOQ7', 'get_ServiceLocator_81LTOQ7Service', true],
            'App\\Controller\\RegisterController:index' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\DashboardController::deleteUser' => '?',
            'App\\Controller\\DashboardController::editUser' => '?',
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\LoginController::logout' => '?',
            'App\\Controller\\LoginController::logoutAjax' => '?',
            'App\\Controller\\ProfileController::index' => '?',
            'App\\Controller\\RegisterController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\DashboardController:deleteUser' => '?',
            'App\\Controller\\DashboardController:editUser' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\LoginController:logout' => '?',
            'App\\Controller\\LoginController:logoutAjax' => '?',
            'App\\Controller\\ProfileController:index' => '?',
            'App\\Controller\\RegisterController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);

        if (isset($container->privates['.service_locator.sv74F8b'])) {
            return $container->privates['.service_locator.sv74F8b'];
        }

        return $container->privates['.service_locator.sv74F8b'] = $instance;
    }
}
