<?php

namespace ContainerCQftBmO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JAjOX00Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JAjOX00' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
        ], [
            'paginator' => '?',
            'repository' => 'App\\Repository\\SessionRepository',
        ]);

        if (isset($container->privates['.service_locator.JAjOX00'])) {
            return $container->privates['.service_locator.JAjOX00'];
        }

        return $container->privates['.service_locator.JAjOX00'] = $instance;
    }
}
