<?php

namespace ContainerCQftBmO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IKdXRMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._iKdXRM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._iKdXRM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'groupe' => ['privates', '.errored..service_locator._iKdXRM.App\\Entity\\Groupe', NULL, 'Cannot autowire service ".service_locator._iKdXRM": it needs an instance of "App\\Entity\\Groupe" but this type has been excluded in "config/services.yaml".'],
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
        ], [
            'groupe' => 'App\\Entity\\Groupe',
            'messageRepository' => 'App\\Repository\\MessageRepository',
        ]);
    }
}
