<?php

namespace ContainerMEayDhV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CK3nB4lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cK3nB4l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
        ], [
            'em' => '?',
            'paginator' => '?',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'sessionRepository' => 'App\\Repository\\SessionRepository',
        ]);

        if (isset($container->privates['.service_locator.cK3nB4l'])) {
            return $container->privates['.service_locator.cK3nB4l'];
        }

        return $container->privates['.service_locator.cK3nB4l'] = $instance;
    }
}
