<?php

namespace ContainerMEayDhV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPerformanceAnalyzerServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PerformanceAnalyzerService' shared autowired service.
     *
     * @return \App\Service\PerformanceAnalyzerService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PerformanceAnalyzerService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\PerformanceAnalyzerService'])) {
            return $container->privates['App\\Service\\PerformanceAnalyzerService'];
        }

        $instance = new \App\Service\PerformanceAnalyzerService($a, ($container->privates['App\\Repository\\TestPassageRepository'] ?? $container->load('getTestPassageRepositoryService')), ($container->privates['App\\Service\\AITextCorrectionService'] ?? $container->load('getAITextCorrectionServiceService')));

        if (isset($container->privates['App\\Service\\PerformanceAnalyzerService'])) {
            return $container->privates['App\\Service\\PerformanceAnalyzerService'];
        }

        return $container->privates['App\\Service\\PerformanceAnalyzerService'] = $instance;
    }
}
