<?php

namespace ContainerRhaM4SP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JQAGcnyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jQAGcny' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cours' => ['privates', '.errored..service_locator.jQAGcny.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.jQAGcny": it needs an instance of "App\\Entity\\Cours" but this type has been excluded in "config/services.yaml".'],
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'niveauRepository' => ['privates', 'App\\Repository\\NiveauRepository', 'getNiveauRepositoryService', true],
            'progressRepository' => ['privates', 'App\\Repository\\UserProgressRepository', 'getUserProgressRepositoryService', true],
        ], [
            'cours' => 'App\\Entity\\Cours',
            'coursRepository' => 'App\\Repository\\CoursRepository',
            'em' => '?',
            'niveauRepository' => 'App\\Repository\\NiveauRepository',
            'progressRepository' => 'App\\Repository\\UserProgressRepository',
        ]);

        if (isset($container->privates['.service_locator.jQAGcny'])) {
            return $container->privates['.service_locator.jQAGcny'];
        }

        return $container->privates['.service_locator.jQAGcny'] = $instance;
    }
}
