<?php

namespace ContainerRhaM4SP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDialogueControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DialogueController' shared autowired service.
     *
     * @return \App\Controller\DialogueController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'DialogueController.php';

        $container->services['App\\Controller\\DialogueController'] = $instance = new \App\Controller\DialogueController();

        $instance->setContainer(($container->privates['.service_locator.f6cOPhg'] ?? $container->load('get_ServiceLocator_F6cOPhgService'))->withContext('App\\Controller\\DialogueController', $container));

        return $instance;
    }
}
