<?php

namespace ContainerYCfXxWs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8HHjGJKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8HHjGJK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aiCorrection' => ['privates', 'App\\Service\\AITextCorrectionService', 'getAITextCorrectionServiceService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'scoringService' => ['privates', 'App\\Service\\TestScoringService', 'getTestScoringServiceService', true],
            'test' => ['privates', '.errored..service_locator.8HHjGJK.App\\Entity\\Test', NULL, 'Cannot autowire service ".service_locator.8HHjGJK": it needs an instance of "App\\Entity\\Test" but this type has been excluded in "config/services.yaml".'],
        ], [
            'aiCorrection' => 'App\\Service\\AITextCorrectionService',
            'entityManager' => '?',
            'scoringService' => 'App\\Service\\TestScoringService',
            'test' => 'App\\Entity\\Test',
        ]);

        if (isset($container->privates['.service_locator.8HHjGJK'])) {
            return $container->privates['.service_locator.8HHjGJK'];
        }

        return $container->privates['.service_locator.8HHjGJK'] = $instance;
    }
}
