<?php

namespace ContainerYCfXxWs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gs8bAG1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gs8bAG1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Gs8bAG1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'langueRepository' => ['privates', 'App\\Repository\\LangueRepository', 'getLangueRepositoryService', true],
            'testRepository' => ['privates', 'App\\Repository\\TestRepository', 'getTestRepositoryService', true],
        ], [
            'langueRepository' => 'App\\Repository\\LangueRepository',
            'testRepository' => 'App\\Repository\\TestRepository',
        ]);
    }
}
