<?php

namespace Container7Lv2uIt;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OWcNa9UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oWcNa9U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tache' => ['privates', '.errored..service_locator.oWcNa9U.App\\Entity\\Tache', NULL, 'Cannot autowire service ".service_locator.oWcNa9U": it needs an instance of "App\\Entity\\Tache" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'tache' => 'App\\Entity\\Tache',
        ]);

        if (isset($container->privates['.service_locator.oWcNa9U'])) {
            return $container->privates['.service_locator.oWcNa9U'];
        }

        return $container->privates['.service_locator.oWcNa9U'] = $instance;
    }
}
