<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Groupe extends \App\Entity\Groupe implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'ID_langue' => [parent::class, 'ID_langue', null, 16],
        "\0".parent::class."\0".'Id_niveau' => [parent::class, 'Id_niveau', null, 16],
        "\0".parent::class."\0".'Id_user' => [parent::class, 'Id_user', null, 16],
        "\0".parent::class."\0".'capacite' => [parent::class, 'capacite', null, 16],
        "\0".parent::class."\0".'date_creation' => [parent::class, 'date_creation', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'messages' => [parent::class, 'messages', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'sessions' => [parent::class, 'sessions', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        'ID_langue' => [parent::class, 'ID_langue', null, 16],
        'Id_niveau' => [parent::class, 'Id_niveau', null, 16],
        'Id_user' => [parent::class, 'Id_user', null, 16],
        'capacite' => [parent::class, 'capacite', null, 16],
        'date_creation' => [parent::class, 'date_creation', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'messages' => [parent::class, 'messages', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'sessions' => [parent::class, 'sessions', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
