<?php

namespace ContainerJKVCdxI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestWorkflowSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\TestWorkflowSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\TestWorkflowSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'TestWorkflowSubscriber.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'MailerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'mailer'.\DIRECTORY_SEPARATOR.'Mailer.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'];
        }
        $b = ($container->privates['mailer.transports'] ?? $container->load('getMailer_TransportsService'));

        if (isset($container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'];
        }
        $c = ($container->services['messenger.default_bus'] ?? self::getMessenger_DefaultBusService($container));

        if (isset($container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'];
        }
        $d = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'];
        }

        $instance = new \App\EventSubscriber\TestWorkflowSubscriber($a, new \Symfony\Component\Mailer\Mailer($b, $c, $d), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));

        if (isset($container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\TestWorkflowSubscriber'] = $instance;
    }
}
