<?php

namespace ContainerLUKT6V2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DscsNrKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DscsNrK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'objectifRepository' => ['privates', 'App\\Repository\\ObjectifRepository', 'getObjectifRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'tacheRepository' => ['privates', 'App\\Repository\\TacheRepository', 'getTacheRepositoryService', true],
        ], [
            'objectifRepository' => 'App\\Repository\\ObjectifRepository',
            'paginator' => '?',
            'tacheRepository' => 'App\\Repository\\TacheRepository',
        ]);

        if (isset($container->privates['.service_locator.DscsNrK'])) {
            return $container->privates['.service_locator.DscsNrK'];
        }

        return $container->privates['.service_locator.DscsNrK'] = $instance;
    }
}
