<?php

namespace ContainerLUKT6V2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExamModeServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ExamModeService' shared autowired service.
     *
     * @return \App\Service\ExamModeService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ExamModeService.php';

        return $container->privates['App\\Service\\ExamModeService'] = new \App\Service\ExamModeService(($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
