<?php

namespace ContainerLUKT6V2;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOpenAIClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\OpenAIClient' shared autowired service.
     *
     * @return \App\Service\OpenAIClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'OpenAIClient.php';

        return $container->privates['App\\Service\\OpenAIClient'] = new \App\Service\OpenAIClient(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('string:AI_API_KEY'), $container->getEnv('string:AI_BASE_URL'), $container->getEnv('string:AI_MODEL'));
    }
}
