<?php

namespace ContainerIN1TZrg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PdeTbKKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PdeTbKK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'groupe' => ['privates', '.errored..service_locator.PdeTbKK.App\\Entity\\Groupe', NULL, 'Cannot autowire service ".service_locator.PdeTbKK": it needs an instance of "App\\Entity\\Groupe" but this type has been excluded in "config/services.yaml".'],
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'groupe' => 'App\\Entity\\Groupe',
            'messageRepository' => 'App\\Repository\\MessageRepository',
            'paginator' => '?',
        ]);

        if (isset($container->privates['.service_locator.PdeTbKK'])) {
            return $container->privates['.service_locator.PdeTbKK'];
        }

        return $container->privates['.service_locator.PdeTbKK'] = $instance;
    }
}
