<?php

namespace ContainerIN1TZrg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGameServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\GameService' shared autowired service.
     *
     * @return \App\Service\GameService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'GameService.php';

        return $container->privates['App\\Service\\GameService'] = new \App\Service\GameService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['App\\Service\\DialogueService'] ?? $container->load('getDialogueServiceService')));
    }
}
