<?php

namespace ContainerFxvLYLY;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XXl0e8GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XXl0e8G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XXl0e8G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'niveauRepository' => ['privates', 'App\\Repository\\NiveauRepository', 'getNiveauRepositoryService', true],
        ], [
            'coursRepository' => 'App\\Repository\\CoursRepository',
            'niveauRepository' => 'App\\Repository\\NiveauRepository',
        ]);
    }
}
