<?php

namespace ContainerFxvLYLY;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PiUkQOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.piUkQ_o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'test' => ['privates', '.errored..service_locator.piUkQ_o.App\\Entity\\Test', NULL, 'Cannot autowire service ".service_locator.piUkQ_o": it needs an instance of "App\\Entity\\Test" but this type has been excluded in "config/services.yaml".'],
            'testPassageStateMachine' => ['privates', 'debug.state_machine.test_passage', 'getDebug_StateMachine_TestPassageService', false],
        ], [
            'em' => '?',
            'test' => 'App\\Entity\\Test',
            'testPassageStateMachine' => '?',
        ]);

        if (isset($container->privates['.service_locator.piUkQ_o'])) {
            return $container->privates['.service_locator.piUkQ_o'];
        }

        return $container->privates['.service_locator.piUkQ_o'] = $instance;
    }
}
