<?php

namespace ContainerFxvLYLY;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JkbqQJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jkbq_QJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'niveau' => ['privates', '.errored..service_locator.jkbq_QJ.App\\Entity\\Niveau', NULL, 'Cannot autowire service ".service_locator.jkbq_QJ": it needs an instance of "App\\Entity\\Niveau" but this type has been excluded in "config/services.yaml".'],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'em' => '?',
            'niveau' => 'App\\Entity\\Niveau',
            'slugger' => '?',
        ]);

        if (isset($container->privates['.service_locator.jkbq_QJ'])) {
            return $container->privates['.service_locator.jkbq_QJ'];
        }

        return $container->privates['.service_locator.jkbq_QJ'] = $instance;
    }
}
