<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container72YNBLX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container72YNBLX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container72YNBLX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container72YNBLX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container72YNBLX\App_KernelDevDebugContainer([
    'container.build_hash' => '72YNBLX',
    'container.build_id' => '7e0a571e',
    'container.build_time' => 1772368392,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container72YNBLX');
