<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKm2rDhd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKm2rDhd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKm2rDhd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKm2rDhd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKm2rDhd\App_KernelDevDebugContainer([
    'container.build_hash' => 'Km2rDhd',
    'container.build_id' => 'b8a80f8c',
    'container.build_time' => 1772311004,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKm2rDhd');
