<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEa0zKRc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEa0zKRc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEa0zKRc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEa0zKRc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEa0zKRc\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ea0zKRc',
    'container.build_id' => 'e1880cf1',
    'container.build_time' => 1770921212,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEa0zKRc');
