<?php

namespace ContainerHco7ISe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gg8faMlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gg8faMl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'test' => ['privates', '.errored..service_locator.gg8faMl.App\\Entity\\Test', NULL, 'Cannot autowire service ".service_locator.gg8faMl": it needs an instance of "App\\Entity\\Test" but this type has been excluded in "config/services.yaml".'],
            'testPassageRepository' => ['privates', 'App\\Repository\\TestPassageRepository', 'getTestPassageRepositoryService', true],
        ], [
            'entityManager' => '?',
            'test' => 'App\\Entity\\Test',
            'testPassageRepository' => 'App\\Repository\\TestPassageRepository',
        ]);

        if (isset($container->privates['.service_locator.gg8faMl'])) {
            return $container->privates['.service_locator.gg8faMl'];
        }

        return $container->privates['.service_locator.gg8faMl'] = $instance;
    }
}
