<?php

namespace ContainerHco7ISe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P3MmV0pService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p3MmV0p' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reponseRepository' => ['privates', 'App\\Repository\\ReponseRepository', 'getReponseRepositoryService', true],
            'test' => ['privates', '.errored..service_locator.p3MmV0p.App\\Entity\\Test', NULL, 'Cannot autowire service ".service_locator.p3MmV0p": it needs an instance of "App\\Entity\\Test" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'reponseRepository' => 'App\\Repository\\ReponseRepository',
            'test' => 'App\\Entity\\Test',
        ]);

        if (isset($container->privates['.service_locator.p3MmV0p'])) {
            return $container->privates['.service_locator.p3MmV0p'];
        }

        return $container->privates['.service_locator.p3MmV0p'] = $instance;
    }
}
